server.port: 19000
spring.application.name: producer
eureka:
  client:
    serviceUrl.defaultZone: http://${EUREKA_SERVER_SERVICE_SERVICE_HOST:127.0.0.1}:${EUREKA_SERVER_SERVICE_SERVICE_HOST:18000}/eureka